#ifndef CNOID_RGLLIDARSENSORPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_RGLLIDARSENSORPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_RGLLIDARSENSORPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_RGLLIDARSENSORPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_RGLLIDARSENSORPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLIMPORT
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLEXPORT
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_RGLLIDARSENSORPLUGIN_STATIC
#  define CNOID_RGLLIDARSENSORPLUGIN_DLLAPI
#  define CNOID_RGLLIDARSENSORPLUGIN_LOCAL
# else
#  ifdef CnoidRGLLIDARSENSORPLUGIN_EXPORTS
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLAPI CNOID_RGLLIDARSENSORPLUGIN_DLLEXPORT
#  else
#   define CNOID_RGLLIDARSENSORPLUGIN_DLLAPI CNOID_RGLLIDARSENSORPLUGIN_DLLIMPORT
#  endif
#  define CNOID_RGLLIDARSENSORPLUGIN_LOCAL CNOID_RGLLIDARSENSORPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_RGLLIDARSENSORPLUGIN_DLLAPI
